"*test*":
  validators:
    is_empty_dataframe: 
    required_columns:
      - ProductName
      - Category
      - Date
      - Value1
      - Value2
      - Value3
      - IsActive
      - IntegerField
      - ProductId
    additional_columns:
      - ProductName
      - Category
      - Date
      - Value1
      - Value2
      - Value3
      - IsActive
      - IntegerField
      - ProductId
    check_null_values:
      columns:
        - Value1
        - Value2
        - Value3
        - IntegerField
      custom_null_values:
        - ""
        - " "
        - "NA"
        - "N/A"
        - "NULL"

    value_range:
      Value1:
        min: 0
        max: 100
      Value2:
        min: 0
      Value3:
        max: 1000
      IntegerField:
        min: 1
        max: 999

"*product_mapping*":
  validators:
    is_empty_dataframe:
    required_columns:
      - Category
      - ProductId
      - ProductName
    additional_columns:
      - Category
      - ProductId
      - ProductName
    check_null_values:
      columns:
        - Category
        - ProductId
        - ProductName
      custom_null_values:
        - ""
        - " "
        - "NA"
        - "N/A"
        - "NULL"
    check_hierarchy:
      higher_level_columns:
        - Category
      lower_level_columns:
        - ProductId
        - ProductName

